
package com.oryx.ws.ref.domain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oryx.ws.service.contact.ContactWSSRequest;
import com.oryx.ws.service.contact.ContactWSSResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactService", targetNamespace = "http://domain.ref.ws.oryx.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oryx.ws.ref.model.ObjectFactory.class,
    com.oryx.ws.service.contact.ObjectFactory.class,
    com.oryx.ws.ref.domain.ObjectFactory.class
})
public interface ContactService {


    /**
     * 
     * @param contactWSSRequest
     * @return
     *     returns com.oryx.ws.service.contact.ContactWSSResponse
     */
    @WebMethod(operationName = "ContactWSS")
    @WebResult(name = "ContactWSSResponse", targetNamespace = "http://com/oryx/ws/service/contact", partName = "ContactWSSResponse")
    public ContactWSSResponse contactWSS(
        @WebParam(name = "ContactWSSRequest", targetNamespace = "http://com/oryx/ws/service/contact", partName = "ContactWSSRequest")
        ContactWSSRequest contactWSSRequest);

}
