
package com.oryx.ws.ref.domain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactServices", targetNamespace = "http://domain.ref.ws.oryx.com", wsdlLocation = "http://localhost:8080/oryx-server/ContactService.wsdl")
public class ContactServices
    extends Service
{

    private final static URL CONTACTSERVICES_WSDL_LOCATION;
    private final static WebServiceException CONTACTSERVICES_EXCEPTION;
    private final static QName CONTACTSERVICES_QNAME = new QName("http://domain.ref.ws.oryx.com", "ContactServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oryx-server/ContactService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTSERVICES_WSDL_LOCATION = url;
        CONTACTSERVICES_EXCEPTION = e;
    }

    public ContactServices() {
        super(__getWsdlLocation(), CONTACTSERVICES_QNAME);
    }

    public ContactServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTSERVICES_QNAME, features);
    }

    public ContactServices(URL wsdlLocation) {
        super(wsdlLocation, CONTACTSERVICES_QNAME);
    }

    public ContactServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTSERVICES_QNAME, features);
    }

    public ContactServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactServiceSoap11")
    public ContactService getContactServiceSoap11() {
        return super.getPort(new QName("http://domain.ref.ws.oryx.com", "ContactServiceSoap11"), ContactService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactServiceSoap11")
    public ContactService getContactServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://domain.ref.ws.oryx.com", "ContactServiceSoap11"), ContactService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTSERVICES_EXCEPTION!= null) {
            throw CONTACTSERVICES_EXCEPTION;
        }
        return CONTACTSERVICES_WSDL_LOCATION;
    }

}
