
package com.oryx.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactService", targetNamespace = "http://com/oryx/ws/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oryx.ws.ObjectFactory.class,
    com.oryx.ws.ref.model.ObjectFactory.class,
    com.oryx.ws.ref.domain.ObjectFactory.class
})
public interface ContactService {


    /**
     * 
     * @param contactWSRequest
     * @return
     *     returns com.oryx.ws.ContactWSResponse
     */
    @WebMethod(operationName = "ContactWS")
    @WebResult(name = "ContactWSResponse", targetNamespace = "http://com/oryx/ws/", partName = "ContactWSResponse")
    public ContactWSResponse contactWS(
        @WebParam(name = "ContactWSRequest", targetNamespace = "http://com/oryx/ws/", partName = "ContactWSRequest")
        ContactWSRequest contactWSRequest);

}
